name: mtbo_py310
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - GPy
  - GPyOpt
  - gymnasium
  - stable_baselines3
  - stable-baselines3[extra]
  - pybullet
  - matplotlib=3.5.0
  - pygame=2.6.0
  - pip
  - pip:
    - box2d-py