name: codesign
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - urdf_parser_py
      - shapely
      - stable-baselines3[extra]
      - panda-gym
      - wandb
      - pyyaml
      - Box2D
      - numpy-stl
      - sb3_contrib
      - ipykernel
